### ISSUE TITLE
 getting status code 500

### ISSUE THREAD

**Issue by Meta-sploit** [jquad-group/backstage-jquad#15]
I am using the tekton plugin. it was working fine but for a few days I am not getting any data, it is throwing some internal server error.
please check if the issue I am getting is because of this only or if it's from my end.
@jizusun 
```
{
  "error": {
    "name": "TypeError",
    "message": "Cannot read properties of undefined (reading 'forEach')",
    "level": "error",
    "service": "backstage"
  },
  "request": {
    "method": "GET",
    "url": "/pipelineruns?namespace=my-namespace&selector="
  },
  "response": {
    "statusCode": 500
  }
}
```

**Comment by rannox** [comment]
Hello,

the error is being thrown, because the tekton plugin backend is trying to read properties, that are not returned from the Kubernetes API Server. 

Which version of the backstage tekton plugin are you using? And what is the version of the Tekton Pipelines on your cluster?

**Comment by Meta-sploit** [comment]
I upgraded the tekton plugin version now it's working.
Thanks
