### ISSUE TITLE
Feature upgrade request

### ISSUE THREAD

**Issue by Meta-sploit** [jquad-group/backstage-jquad#16]
The Tekton plugin is fantastic and it has all the features that helps a developer to check the status of pipelines and task runs, but one thing that can be improved is  **show logs** for taskrun, it redirects to some non-formatted text (Logs).
also, there is no back button so it's not a good user experience. 
Please provide logs in the structured format as we see in the tekton dashboard.
please look into it. @rannox @n-kostadinov @jizusun

**Comment by rannox** [comment]
Thank you very much for the feedback @Meta-sploit! Will try to implement it the following days.

**Comment by Meta-sploit** [comment]
In `stepLog.tsx` 


For the back button
Either page can be reloaded like this 
```<Button onClick={() => window.location.reload()}>Go back</Button>```
or it can be rendered to the previous route 
```<Button onClick={() => navigate(-1)}>Go back</Button>```





Box can be changed to something like this
```function NewlineText(props: { text: string }): JSX.Element {
  const text = props.text;
  const newText = text.split('\n').map(str => <p>{str}</p>);
  return (
    <>
      <Paper
        elevation={3}
        style={{
          padding: 16,
          margin: 'auto',
          maxWidth: 1000,
          backgroundColor: 'black',
          color: 'white',
        }}
      >
        <Typography variant="body1">{newText}</Typography>
      </Paper>
    </>
  );
}```

**Comment by rannox** [comment]
Also added a fullscreen mode for the logs dialog

**Comment by Meta-sploit** [comment]
It's great to see the improvements. I'm looking forward to utilizing this feature on my backstage instance once it's released under the new version. Thank you for all your hard work.

**Comment by rannox** [comment]
You are welcome, and thank you for your valuable feedback :)

Just released the new version, you can close the issue if everything is okay :)

**Comment by Meta-sploit** [comment]
Everything is operating smoothly, and I am closing the issue with this comment
