### ISSUE TITLE
Optional Header for the DashBoard

### ISSUE THREAD

**Issue by Meta-sploit** [jquad-group/backstage-jquad#20]
The Tekton dashboard currently has a default header that can be made optional. This feature would be useful when adding the Tekton plugin to the `serviceEntityPage` or `websiteEntityPage` as it would prevent the addition of an extra header and save space. A boolean value could be used to specify whether or not to display the header.

![image](https://user-images.githubusercontent.com/125371773/234781068-efdd38ef-ce29-4dce-8520-6dd9d58410b3.png)

**Comment by rannox** [comment]
You are right, we don't need this header at all. It contains a redundant information and uses additional space. I will just remove it.

**Comment by rannox** [comment]
it is implemented in v0.3.3 :) 
Can you check if this works for you?

**Comment by Meta-sploit** [comment]
The issue appears to be resolved as I have checked it on my end and it seems to be working fine. Therefore, I am closing the issue with this comment.
